# Generated by Django 5.1.7 on 2025-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Expired'), (3, 'Cancelled'), (4, 'Pending')], default=4),
        ),
    ]
