# Generated by Django 5.1.7 on 2025-04-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
