# Generated by Django 5.1.7 on 2025-05-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0002_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gym_feedback',
            field=models.BooleanField(default=False, help_text='Đánh giá về phòng gym/chất lượng dịch vụ chung'),
        ),
        migrations.AddField(
            model_name='review',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gymcareapp.trainer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='gymcareapp.member'),
        ),
        migrations.AlterField(
            model_name='review',
            name='training_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gymcareapp.trainingpackage'),
        ),
    ]
