# Generated by Django 5.1.7 on 2025-03-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0002_typepackage_workoutprogress_member_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
