# Generated by Django 5.0.6 on 2025-06-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0003_promotion_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('predicted_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('predicted_body_fat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('predicted_muscle_mass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence', models.FloatField()),
                ('next_check_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='gymcareapp.member')),
            ],
        ),
    ]
