# Generated by Django 5.1.7 on 2025-03-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0004_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutschedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Completed'), (2, 'Cancelled'), (3, 'Pending_change'), (4, 'Changed')], default=0),
        ),
        migrations.CreateModel(
            name='WorkoutScheduleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('proposed_time', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='gymcareapp.workoutschedule')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='gymcareapp.trainer')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
