# Generated by Django 5.1.7 on 2025-03-26 02:08

import gymcareapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0005_alter_workoutschedule_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingpackage',
            name='type_package',
            field=models.IntegerField(choices=[(0, 'Month'), (1, 'Quarter'), (2, 'Year')], default=gymcareapp.models.TypePackage['MONTH']),
        ),
        migrations.DeleteModel(
            name='TypePackage',
        ),
    ]
