# Generated by Django 5.1.7 on 2025-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0008_report_member_gender_trainingpackage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
