# Generated by Django 5.1.7 on 2025-04-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0011_alter_member_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
