# Generated by Django 5.1.7 on 2025-04-03 10:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0012_alter_member_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='certification',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
