# Generated by Django 5.1.7 on 2025-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0013_alter_trainer_certification_alter_trainer_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingpackage',
            name='end_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trainingpackage',
            name='start_date',
            field=models.TimeField(),
        ),
    ]
