# Generated by Django 5.1.7 on 2025-04-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0014_alter_trainingpackage_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingpackage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trainingpackage',
            name='start_date',
        ),
    ]
