# Generated by Django 5.1.7 on 2025-04-03 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0015_remove_trainingpackage_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutprogress',
            options={'ordering': ['-created_date'], 'verbose_name': 'Workout Progress', 'verbose_name_plural': 'Workout Progresses'},
        ),
        migrations.AddField(
            model_name='workoutprogress',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='gymcareapp.member'),
            preserve_default=False,
        ),
    ]
