# Generated by Django 5.1.7 on 2025-04-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0016_alter_workoutprogress_options_workoutprogress_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
