# Generated by Django 5.1.7 on 2025-04-04 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0017_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 4, 17, 13, 5, 69375, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Expired'), (3, 'Cancelled'), (4, 'Pending')], default=4),
        ),
    ]
