# Generated by Django 5.1.7 on 2025-04-05 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0018_subscription_end_date_subscription_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
