# Generated by Django 5.1.7 on 2025-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0019_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_url',
            field=models.ImageField(blank=True, null=True, upload_to='payments/%Y/%m/'),
        ),
    ]
