# Generated by Django 5.1.7 on 2025-04-09 17:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0020_alter_payment_options_alter_payment_receipt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_url',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dohsfqs6d/image/upload/v1742786537/gymcare/user.png', max_length=255, verbose_name='avatar'),
        ),
    ]
