# Generated by Django 5.1.7 on 2025-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0021_alter_payment_receipt_url_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingpackage',
            old_name='total_cost',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='subscription',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
