# Generated by Django 5.1.7 on 2025-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0022_rename_total_cost_trainingpackage_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutschedule',
            name='scheduled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
