# Generated by Django 5.1.7 on 2025-04-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymcareapp', '0007_alter_user_phone'),
        ('gymcareapp', '0023_alter_workoutschedule_scheduled_at'),
    ]

    operations = [
    ]
