#version: '3.8'
#
#services:
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"  # Mở cổng Redis từ Docker sang máy chủ của bạn
#
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000  # Chạy Django trong Docker
#    volumes:
#      - .:/app  # Mount thư mục dự án vào container
#    ports:
#      - "8000:8000"  # Mở cổng 8000 của Django
#    depends_on:
#      - redis
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0  # Cấu hình kết nối đến Redis từ Celery
#
#  celery_worker:
#    build: .
#    command: celery -A gymcare worker --loglevel=info  # Chạy Celery worker trong Docker
#    volumes:
#      - .:/app  # Mount thư mục dự án vào container
#    depends_on:
#      - redis  # Celery cần Redis
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0  # Cấu hình kết nối đến Redis từ Celery

services:
  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

  web:
    build: .
    container_name: django_app
    command: >
      bash -c "sleep 10  && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
    environment:
      - DB_HOST=host.docker.internal
      - DB_NAME=${DB_NAME:-gymcaredb}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_ROOT_PASSWORD:-Admin@123}
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=${DEBUG:-0}
    env_file:
      - .env
    networks:
      - app_network
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A gymcare worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DB_HOST=host.docker.internal
      - DB_NAME=${DB_NAME:-gymcaredb}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_ROOT_PASSWORD:-Admin@123}
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  app_network:
    driver: bridge